{% set name = "foundry-platform-sdk" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/foundry_platform_sdk-{{ version }}.tar.gz
  sha256: 72eddfface4837dd4d07654d39d686bcc37682ae8e29cc7b419ac2d94236aa5e

build:
  entry_points:
    - foundry = foundry.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<4.0
    - setuptools >=35.0.2
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.9.0,<4.0.0
    - requests >=2.25.0,<3.0.0
    - pydantic >=2.1.0,<3.0.0
    - typing-extensions >=4.7.1

test:
  imports:
    - foundry
  commands:
    - pip check
    - foundry --help
  requires:
    - pip
    - click

about:
  home: https://github.com/palantir/foundry-platform-python
  summary: The official Python library for the Foundry API
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jsmith
    - tdeitch
    - jameszhang244
