{% set name = "foundry-platform-sdk" %}
{% set version = "0.40.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/foundry_platform_sdk-{{ version }}.tar.gz
  sha256: dbcb288ca48e68c2970a8d993b8f489b3f280f36e26d8596a4ba4c40e8db3266

build:
  entry_points:
    - foundry_v1 = foundry.v1.cli:cli
    - foundry_v2 = foundry.v2.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<4.0
    - setuptools >=35.0.2
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.9.0,<4.0.0
    - requests >=2.25.0,<3.0.0
    - pydantic >=2.1.0,<3.0.0
    - typing-extensions >=4.7.1

test:
  imports:
    - foundry
  commands:
    - pip check
    - foundry_v2 --help
  requires:
    - pip
    - click

about:
  home: https://github.com/palantir/foundry-platform-python
  summary: The official Python library for the Foundry API
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jsmith
    - tdeitch
    - jameszhang244
